### ISSUE TITLE
opendata/res/

### ISSUE THREAD

**Issue by ljk123** [ForeverZi/opendatarank#2]
opendata/res/ 能提供参考下吗

**Comment by ForeverZi** [comment]
这些资源和项目相关，不能提供哈。不过这是一个排行榜范例，所以按照文件命基本可以推断出大致的图片样式。周末的话我可以更新下这个仓库，加上范例图片，如果不急的话可以等到下周。

**Comment by ljk123** [comment]
好的谢谢

**Comment by ForeverZi** [comment]
已添加示例和资源
